{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubeidle.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch", "update"]
{{- end }}